"use client";

/*
 * ProjectAIAssistant — engineer-side AI Q&A box.
 *
 * Sits in the right rail of the engineer's session room during an
 * active call. The engineer can ask natural-language questions
 * about the customer's project ("what was last session about?",
 * "what files did they share?", "what stack are they on?") and the
 * server-side /api/staff/project-qa route proxies to OpenAI with
 * full project context loaded (past session summaries + chat
 * transcripts + file metadata).
 *
 * The Zoom call usually runs in a SEPARATE window on the engineer's
 * desktop — so the engineer can read the customer's context here
 * while talking on the call. Hands-on UX optimization: short
 * answers, fast turn-around, no extra chrome.
 *
 * State is local — there's no server-side persistence of the Q&A
 * history. Each session room mount starts a fresh thread. That's
 * deliberate: the assistant is a scratchpad, not a transcript.
 */

import { useCallback, useEffect, useRef, useState } from "react";
import {
  Sparkles,
  Send,
  Loader2,
  History as HistoryIcon,
  Plus,
  Copy,
  Check,
  ChevronRight,
  MessageSquare,
} from "lucide-react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { createClient } from "@/lib/supabase/browser";

const BRAND_GREEN = "var(--primary)";
const BRAND_GREEN_SOFT = "var(--primary-soft)";

type Message =
  | { role: "user"; content: string; id: string }
  | { role: "assistant"; content: string; id: string; fallback?: string };

type HistRow = {
  id: string;
  thread_id: string;
  role: "user" | "assistant";
  content: string;
  user_name: string | null;
  created_at: string;
};
type HistThread = {
  threadId: string;
  asker: string;
  startedAt: string;
  rows: HistRow[];
};

export function ProjectAIAssistant({
  projectId,
  projectName,
}: {
  projectId: string | null;
  /** Display-only — used to label the panel header. The API hydrates
   *  the real project context from projectId server-side. */
  projectName?: string | null;
}) {
  const [messages, setMessages] = useState<Message[]>([]);
  const [draft, setDraft] = useState("");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const scrollRef = useRef<HTMLDivElement>(null);
  // One conversation = one thread id (regenerated by "New chat"). Sent to the
  // route so the shared project history groups each Q&A into a thread.
  const threadIdRef = useRef<string>(crypto.randomUUID());
  const [view, setView] = useState<"chat" | "history">("chat");
  const [historyThreads, setHistoryThreads] = useState<HistThread[]>([]);
  const [historyLoading, setHistoryLoading] = useState(false);

  const loadHistory = useCallback(async () => {
    if (!projectId) return;
    setHistoryLoading(true);
    try {
      const sb = createClient();
      const { data } = await sb
        .from("project_assistant_messages")
        .select("id, thread_id, role, content, user_name, created_at")
        .eq("project_id", projectId)
        .order("created_at", { ascending: true });
      const rows = (data ?? []) as HistRow[];
      const map = new Map<string, HistThread>();
      for (const r of rows) {
        let t = map.get(r.thread_id);
        if (!t) {
          t = {
            threadId: r.thread_id,
            asker: r.user_name ?? "Staff",
            startedAt: r.created_at,
            rows: [],
          };
          map.set(r.thread_id, t);
        }
        t.rows.push(r);
      }
      setHistoryThreads(
        Array.from(map.values()).sort(
          (a, b) =>
            new Date(b.startedAt).getTime() - new Date(a.startedAt).getTime()
        )
      );
    } finally {
      setHistoryLoading(false);
    }
  }, [projectId]);

  const toggleHistory = useCallback(() => {
    setView((v) => {
      if (v === "chat") {
        void loadHistory();
        return "history";
      }
      return "chat";
    });
  }, [loadHistory]);

  const newChat = useCallback(() => {
    threadIdRef.current = crypto.randomUUID();
    setMessages([]);
    setError(null);
    setView("chat");
  }, []);

  // Resume a past conversation: load its turns into the live chat and adopt its
  // thread id, so the next question continues the SAME thread (and is saved
  // under it). Switches from history → chat.
  const resumeThread = useCallback((thread: HistThread) => {
    threadIdRef.current = thread.threadId;
    setMessages(
      thread.rows.map((r) =>
        r.role === "user"
          ? { role: "user" as const, content: r.content, id: r.id }
          : { role: "assistant" as const, content: r.content, id: r.id },
      ),
    );
    setError(null);
    setView("chat");
  }, []);

  // Auto-scroll to the latest message as the conversation grows.
  useEffect(() => {
    const el = scrollRef.current;
    if (!el) return;
    el.scrollTop = el.scrollHeight;
  }, [messages.length, busy]);

  const send = useCallback(async () => {
    const question = draft.trim();
    if (!question || busy || !projectId) return;
    const userMsg: Message = {
      role: "user",
      content: question,
      id: crypto.randomUUID(),
    };
    setMessages((prev) => [...prev, userMsg]);
    setDraft("");
    setBusy(true);
    setError(null);
    try {
      // Build history pairs for the model — strip our id field. We
      // include all prior turns so the engineer can ask follow-ups
      // ("ok, when was that?", "and the engineer's name?").
      const history = messages.map((m) => ({
        role: m.role,
        content: m.content,
      }));
      const res = await fetch("/api/staff/project-qa", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          projectId,
          question,
          history,
          threadId: threadIdRef.current,
        }),
      });
      const json = (await res.json()) as {
        text?: string;
        fallback?: string;
        error?: string;
      };
      if (!res.ok)
        throw new Error(json.error ?? `Server returned ${res.status}`);
      const text = json.text ?? "AI returned no answer. Try rephrasing.";
      setMessages((prev) => [
        ...prev,
        {
          role: "assistant",
          content: text,
          id: crypto.randomUUID(),
          fallback: json.fallback,
        },
      ]);
    } catch (e) {
      const msg =
        e instanceof Error ? e.message : "Couldn't reach the AI service.";
      setError(msg);
    } finally {
      setBusy(false);
    }
  }, [draft, busy, projectId, messages]);

  const onKeyDown = (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
    if (e.key === "Enter" && !e.shiftKey && !e.nativeEvent.isComposing) {
      e.preventDefault();
      void send();
    }
  };

  return (
    <section
      className="flex h-full flex-col border-l"
      style={{
        borderColor: "var(--border)",
        backgroundColor: "var(--surface)",
      }}
    >
      {/* Header — Sparkles + label + project name. Keeps the panel
          unambiguously branded as "AI", not "another chat". */}
      <div
        className="flex shrink-0 items-center gap-2 border-b px-4 py-3"
        style={{ borderColor: "var(--border)" }}
      >
        <span
          className="relative flex h-7 w-7 shrink-0 items-center justify-center rounded-full"
          style={{ backgroundColor: BRAND_GREEN_SOFT, color: BRAND_GREEN }}
        >
          <Sparkles size={13} />
          {/* Status dot — pulses green while the assistant is answering. */}
          <span
            aria-hidden
            className="absolute -right-0.5 -bottom-0.5 h-2 w-2 rounded-full border-2"
            style={{
              backgroundColor: "var(--green-dot, var(--primary))",
              borderColor: "var(--surface)",
              animation: busy
                ? "relay-pulse-ok 1.2s ease-in-out infinite"
                : undefined,
            }}
          />
        </span>
        <div className="min-w-0 flex-1">
          <div
            className="text-[12px] font-semibold tracking-wider uppercase"
            style={{ color: "var(--text)" }}
          >
            AI project assistant
          </div>
          <div
            className="truncate text-[10px]"
            style={{ color: "var(--text-muted)" }}
          >
            {view === "history"
              ? "Shared history — everyone on this project"
              : projectName
                ? `Context for ${projectName}`
                : "Project context auto-loaded"}
          </div>
        </div>
        <div className="flex shrink-0 items-center gap-0.5">
          <button
            type="button"
            onClick={newChat}
            title="New chat"
            aria-label="New chat"
            className="flex h-7 w-7 items-center justify-center rounded-md transition-colors hover:bg-black/5 dark:hover:bg-white/5"
            style={{ color: "var(--text-muted)" }}
          >
            <Plus size={15} />
          </button>
          <button
            type="button"
            onClick={toggleHistory}
            title={view === "history" ? "Back to chat" : "History"}
            aria-label="History"
            aria-pressed={view === "history"}
            className="flex h-7 w-7 items-center justify-center rounded-md transition-colors hover:bg-black/5 dark:hover:bg-white/5"
            style={{
              color: view === "history" ? BRAND_GREEN : "var(--text-muted)",
              backgroundColor:
                view === "history" ? BRAND_GREEN_SOFT : undefined,
            }}
          >
            <HistoryIcon size={15} />
          </button>
        </div>
      </div>

      {/* Body — message thread + empty-state coaching */}
      <div
        ref={scrollRef}
        className="hide-scrollbar flex-1 overflow-y-auto px-4 py-4"
      >
        {view === "history" ? (
          <HistoryPanel
            threads={historyThreads}
            loading={historyLoading}
            onResume={resumeThread}
          />
        ) : messages.length === 0 && !busy ? (
          <EmptyState />
        ) : (
          <div className="space-y-3">
            {messages.map((m) =>
              m.role === "user" ? (
                <UserBubble key={m.id} text={m.content} />
              ) : (
                <AssistantBubble
                  key={m.id}
                  text={m.content}
                  fallback={m.fallback}
                />
              )
            )}
            {busy && <AssistantThinking />}
          </div>
        )}
      </div>

      {/* Composer — single textarea + send. Enter to send, Shift+
          Enter for newline. Hidden while viewing history. */}
      {view === "chat" && (
        <div
          className="shrink-0 border-t p-3"
          style={{ borderColor: "var(--border)" }}
        >
          {error && (
            <p
              className="mb-2 text-[11px]"
              style={{ color: "var(--accent-red)" }}
            >
              {error}
            </p>
          )}
          {!projectId && (
            <p
              className="mb-2 text-[11px]"
              style={{ color: "var(--text-muted)" }}
            >
              No project bound to this session — the assistant has nothing to
              look up.
            </p>
          )}
          <div className="flex items-end gap-2">
            <textarea
              value={draft}
              onChange={(e) => setDraft(e.target.value)}
              onKeyDown={onKeyDown}
              placeholder={
                projectId
                  ? "Ask about this project…"
                  : "No project — assistant disabled"
              }
              disabled={busy || !projectId}
              rows={2}
              className="block w-full resize-none rounded-md border bg-transparent px-2.5 py-2 text-[13px] outline-none focus:ring-2 disabled:opacity-50"
              style={{
                borderColor: "var(--border)",
                color: "var(--text)",
                ["--tw-ring-color" as string]:
                  "color-mix(in srgb, var(--primary) 35%, transparent)",
              }}
            />
            <button
              type="button"
              onClick={() => void send()}
              disabled={busy || !draft.trim() || !projectId}
              aria-label="Send"
              className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full transition-opacity hover:opacity-90 disabled:cursor-not-allowed disabled:opacity-40"
              style={{ backgroundColor: BRAND_GREEN, color: "#fff" }}
            >
              {busy ? (
                <Loader2 size={14} className="animate-spin" />
              ) : (
                <Send size={14} />
              )}
            </button>
          </div>
        </div>
      )}
    </section>
  );
}

// ── Subcomponents ────────────────────────────────────────────────────

function relTime(iso: string): string {
  const ms = Date.now() - new Date(iso).getTime();
  if (Number.isNaN(ms) || ms < 60_000) return "just now";
  const m = Math.floor(ms / 60_000);
  if (m < 60) return `${m}m ago`;
  const h = Math.floor(m / 60);
  if (h < 24) return `${h}h ago`;
  const d = Math.floor(h / 24);
  if (d < 30) return `${d}d ago`;
  return new Date(iso).toLocaleDateString([], {
    month: "short",
    day: "numeric",
  });
}

/** A thread's title = the first question asked in it. */
function threadTitle(t: HistThread): string {
  const firstQ = t.rows.find((r) => r.role === "user");
  return firstQ?.content.trim() || "Conversation";
}

function HistoryPanel({
  threads,
  loading,
  onResume,
}: {
  threads: HistThread[];
  loading: boolean;
  onResume: (thread: HistThread) => void;
}) {
  if (loading) {
    return (
      <div
        className="flex h-full items-center justify-center py-12"
        style={{ color: "var(--text-muted)" }}
      >
        <Loader2 size={16} className="animate-spin" />
      </div>
    );
  }
  if (threads.length === 0) {
    return (
      <p
        className="px-2 py-12 text-center text-[12px]"
        style={{ color: "var(--text-muted)" }}
      >
        No questions asked about this project yet. Anything you ask is saved
        here for the whole team.
      </p>
    );
  }

  // Tapping a past conversation resumes it straight into the chat (its turns +
  // a live composer), so the supervisor can read it AND keep asking — the
  // follow-ups continue the same saved thread.
  return (
    <ul className="space-y-1.5">
      {threads.map((t) => {
        const questions = t.rows.filter((r) => r.role === "user").length;
        return (
          <li key={t.threadId}>
            <button
              type="button"
              onClick={() => onResume(t)}
              title="Open & continue this chat"
              className="flex w-full items-center gap-2.5 rounded-lg border px-3 py-2.5 text-left transition-colors hover:bg-black/[0.03] dark:hover:bg-white/[0.04]"
              style={{ borderColor: "var(--border)" }}
            >
              <MessageSquare
                size={14}
                className="shrink-0"
                style={{ color: BRAND_GREEN }}
              />
              <div className="min-w-0 flex-1">
                <div
                  className="truncate text-[13px] font-medium"
                  style={{ color: "var(--text)" }}
                >
                  {threadTitle(t)}
                </div>
                <div
                  className="truncate text-[10px]"
                  style={{ color: "var(--text-faint)" }}
                >
                  {t.asker} · {relTime(t.startedAt)}
                  {questions > 1 ? ` · ${questions} questions` : ""}
                </div>
              </div>
              <ChevronRight
                size={14}
                className="shrink-0"
                style={{ color: "var(--text-muted)" }}
              />
            </button>
          </li>
        );
      })}
    </ul>
  );
}

function EmptyState() {
  return (
    <div className="flex h-full flex-col items-center justify-center py-12 text-center">
      <div
        className="mb-3 flex h-10 w-10 items-center justify-center rounded-full"
        style={{ backgroundColor: BRAND_GREEN_SOFT, color: BRAND_GREEN }}
      >
        <Sparkles size={18} />
      </div>
      <p
        className="max-w-[280px] text-[13px] font-medium"
        style={{ color: "var(--text)" }}
      >
        Quick context, no scroll.
      </p>
      <p
        className="mt-1.5 max-w-[280px] text-[11.5px] leading-relaxed"
        style={{ color: "var(--text-muted)" }}
      >
        Ask anything about this project — past sessions, files shared, stack
        used, pending next steps. The AI has full project memory.
      </p>
      <ul
        className="mt-2 flex flex-col gap-1 text-left text-[11px]"
        style={{ color: "var(--text-faint)" }}
      >
        <li>— What was last session about?</li>
        <li>— Which files has the customer shared?</li>
        <li>— What&apos;s still open from last call?</li>
      </ul>
    </div>
  );
}

function UserBubble({ text }: { text: string }) {
  return (
    <div className="flex justify-end">
      <div
        className="max-w-[85%] rounded-2xl px-3 py-2 text-[13px] leading-relaxed"
        style={{
          backgroundColor: BRAND_GREEN,
          color: "#fff",
          borderBottomRightRadius: 6,
        }}
      >
        {text}
      </div>
    </div>
  );
}

function AssistantBubble({
  text,
  fallback,
}: {
  text: string;
  fallback?: string;
}) {
  const [copied, setCopied] = useState(false);
  const copy = async () => {
    try {
      await navigator.clipboard.writeText(text);
    } catch {
      const el = document.createElement("textarea");
      el.value = text;
      el.style.position = "fixed";
      el.style.opacity = "0";
      document.body.appendChild(el);
      el.select();
      try {
        document.execCommand("copy");
      } catch {
        /* nothing more we can do */
      }
      el.remove();
    }
    setCopied(true);
    setTimeout(() => setCopied(false), 1500);
  };
  return (
    <div className="group flex items-start gap-2">
      <span
        aria-hidden
        className="mt-0.5 flex h-6 w-6 shrink-0 items-center justify-center rounded-full"
        style={{ backgroundColor: BRAND_GREEN_SOFT, color: BRAND_GREEN }}
      >
        <Sparkles size={11} />
      </span>
      <div className="min-w-0 flex-1">
        <div
          className="rounded-2xl px-3 py-2"
          style={{
            backgroundColor: "color-mix(in srgb, var(--text) 6%, transparent)",
            color: "var(--text)",
            borderBottomLeftRadius: 6,
          }}
        >
          <div className="assistant-md">
            <ReactMarkdown remarkPlugins={[remarkGfm]}>{text}</ReactMarkdown>
          </div>
        </div>
        <div className="mt-1 flex items-center gap-2">
          <button
            type="button"
            onClick={() => void copy()}
            className="inline-flex items-center gap-1 text-[10px] opacity-0 transition-opacity group-hover:opacity-100 focus:opacity-100"
            style={{ color: copied ? BRAND_GREEN : "var(--text-faint)" }}
          >
            {copied ? <Check size={10} /> : <Copy size={10} />}
            {copied ? "Copied" : "Copy"}
          </button>
          {fallback && (
            <span
              className="text-[9px] tracking-wider uppercase"
              style={{ color: "var(--text-faint)" }}
            >
              {fallback === "no_key"
                ? "offline mode"
                : fallback === "openai_error"
                  ? "ai unreachable"
                  : fallback === "no_context"
                    ? "no project history yet"
                    : fallback}
            </span>
          )}
        </div>
      </div>
    </div>
  );
}

function AssistantThinking() {
  return (
    <div className="flex items-start gap-2">
      <span
        aria-hidden
        className="mt-0.5 flex h-6 w-6 shrink-0 items-center justify-center rounded-full"
        style={{ backgroundColor: BRAND_GREEN_SOFT, color: BRAND_GREEN }}
      >
        <Sparkles size={11} />
      </span>
      <div
        className="rounded-2xl px-3 py-2 text-[13px] leading-relaxed"
        style={{
          backgroundColor: "color-mix(in srgb, var(--text) 6%, transparent)",
          color: "var(--text-muted)",
          borderBottomLeftRadius: 6,
        }}
      >
        <span
          className="inline-flex items-center gap-1"
          aria-label="Assistant is typing"
        >
          {[0, 1, 2].map((i) => (
            <span
              key={i}
              className="inline-block h-1.5 w-1.5 rounded-full"
              style={{
                backgroundColor: "var(--text-muted)",
                animation: "relay-typing 1.2s ease-in-out infinite",
                animationDelay: `${i * 0.18}s`,
              }}
            />
          ))}
        </span>
      </div>
    </div>
  );
}
